### ISSUE TITLE
Suppress Boost warnings?

### ISSUE THREAD

**Issue by eddelbuettel** [asieira/SnakeCharmR#29] opened 2016-09-12 14:57 UTC
I see

```
In file included from /usr/include/python2.7/Python.h:86:0,
                 from python.cpp:4:
/usr/include/python2.7/intobject.h:46:15: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyInt_AsUnsignedLongLongMask(PyObject *);
               ^
In file included from /usr/include/python2.7/Python.h:88:0,
                 from python.cpp:4:
/usr/include/python2.7/longobject.h:50:37: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PyObject *) PyLong_FromLongLong(PY_LONG_LONG);
                                     ^
/usr/include/python2.7/longobject.h:51:54: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PyObject *) PyLong_FromUnsignedLongLong(unsigned PY_LONG_LONG);
                                                      ^
/usr/include/python2.7/longobject.h:52:6: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLong(PyObject *);
      ^
/usr/include/python2.7/longobject.h:53:15: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLong(PyObject *);
               ^
/usr/include/python2.7/longobject.h:54:15: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLongMask(PyObject *);
               ^
/usr/include/python2.7/longobject.h:55:6: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLongAndOverflow(PyObject *, int *);
```

The usual trick around it is to move to C++11 compilation as the (very narrow) old C++ standard does not know `long long`.  You could just add

```
## We want C++11 
CXX_STD = CXX11
```

to `src/Makevars` as a number of packages do.

**Comment by asieira** [comment] 2016-09-12 20:02
Thank you, @eddelbuettel. I never saw those warnings on my own tests, but I'll test the change you suggested.

**Comment by eddelbuettel** [comment] 2016-09-12 20:17
Awesome.  For what it is worth I always build with these flags (and similarly for `CFLAGS` and `CXX1XFLAGS`) 

```
CXXFLAGS +=           -O3 -Wall -pipe -Wno-unused -pedantic
```

and I think at least at some point CRAN reported back. The lack of `long long` (in the old C++ standard) can actually be a real issue, especially for a package like your which interacts with another language having the type.  For RcppCNPy I had to suppress int support on old systems; now that even Windows has g++-4.9.\* it is all better and I just impose C++11.

**Comment by asieira** [comment] 2016-09-12 20:26
@hrbrmstr @Ironholds @bhaskarvk you are probably much more qualified than I am to judge what's being suggested here, what are you thoughts?

**Comment by eddelbuettel** [comment] 2016-09-12 20:35
I wish I had a better canonical reference for this, but in essence
- without C++11 you have no `long long`, see eg [what I had to do in RcppCNPy until 2014](https://github.com/eddelbuettel/rcppcnpy/commit/f29148857d2f406341361504a9e78350d16d415d) -- scroll down in the diff to see the `#ifdef` no longer required after switching to C++11 everywhere
- you need `long long` as Python has it, so user may send you data that way
- the fix is simple as R supports it formally on all platform -- just add the line I suggested to `src/Makevars`

**Comment by asieira** [comment] 2016-09-12 20:40
One interesting aspect of this is that I only ever call a truly small subset of Python API functions that handle str and unicode types. I never call any that has `long long` parameters or return types. So I wonder if requiring C++11 is actually necessary in this case. What do you think?

**Comment by bhaskarvk** [comment] 2016-09-12 21:27
I think you still need to add it coz Python header files have stuff in it that depends on C++11.  I'm no  C++ expert so take my advice with a grain of salt.

**Comment by asieira** [comment] 2016-09-13 13:10
The more I think about it, the more I lean towards "if it ain't broke, don't fix it".

@eddelbuettel I appreciate you bringing up the warnings, but they are just that: warnings. And even using the exact CFLAGS you mentioned above I was never able to reproduce this and get the same warnings you did on my test environments. Maybe there's something specific about your environment, such as other settings in your ~/.R/Makevars or the way you compiled Python, that is causing this.

SnakeCharmR has compiled and worked correctly (including passing all tests) on all environments I tested it in so far, including different Linux distros and on OS X with g++ and clang.  I can see how not having `long long` support has serious implications for RcppCNPy, but since SnakeCharmR does not need to use `long long` at all I don't see how this would affect it unless something like a compilation error happened.

So I ended up reviewing and cleaning up `configure.ac` from a few unwanted things, but I did not add the line suggested to `src/Makevars` as I've seen no evidence so far that it is at all necessary.

I'll close this ticket now, but I'll be more than happy to reopen it if some further evidence comes up of a reproducible scenario where not setting this actually causes some sort of impact to users.

Thanks again for your help and suggestions.

**Comment by eddelbuettel** [comment] 2016-09-13 14:05
Dude, the warnings are from the compiler, not from me.

I am uninstalling this from by box.

**Comment by asieira** [comment] 2016-09-16 15:12
@bhaskarvk recently brought to my attention a wonderful blog post from @kevinushey that explains why this is necessary in much greater detail: http://kevinushey.github.io/blog/2016/09/14/pitfalls-in-writing-portable-c++98-code/

Reopening this and implementing the recommendation to add `CXX_STD = CXX11` to `src/Makevars` as originally suggested by @eddelbuettel.

**Closed as completed** 2016-09-16 15:31 UTC
Labels: enhancement
